### PR TITLE
Improve example for first time users

### PR DESCRIPTION
**Pull request by TWiStErRob**
I started using Notion and this lib in the past two days. Both great productivity boosts, thanks! I wrote a few import scripts, including a CSV importer because the built-in one just says "Error" without any help. While doing so I noticed a few things in the example that would've made it easier to start off.
 * Use more kotlin-y functions and style (`single`, `error`, wrapping, `[]`, `first`)
 * Minor updates to comments
 * Inline `prop` as it was confusing on first read (and this snipped should be optimized for a cold-read).
 * Bang!! a few things to make them non-null. They make no sense if they were null, so fail fast.
 * Extracted a small utility because almost every time a String is inserted, it has to be Rich.

I recommend to squash this PR.

### CODE REVIEW

**Review by seratch — CHANGES_REQUESTED** [review]
Thank you! The reasons that you mention in the description make sense to me. 

One extra thing that I'd like you to work on is to update the test code to verify the code compiles and works: https://github.com/seratch/notion-sdk-jvm/blob/main/core/src/test/kotlin/readme.kt

Can you update the test code? Also, please apply code formatter (https://github.com/seratch/notion-sdk-jvm/blob/main/scripts/format.sh) to it before committing the change.

**Comment by TWiStErRob** [comment]
Uuuh, ok, update the file: https://github.com/seratch/notion-sdk-jvm/pull/80/commits/16e1a68d9d331c662c1b7d7480cccfa16d688008.
I copied the changed code from README.md to readme.kt and ran what's the CI (`test-compile test`). I observed:
```
[WARNING] P:\projects\contrib\github-notion-sdk-jvm\core\src\test\kotlin\readme.kt: (51, 9) Variable 'updatedPage' is never used
[WARNING] P:\projects\contrib\github-notion-sdk-jvm\core\src\test\kotlin\readme.kt: (60, 9) Variable 'retrievedPage' is never used
```
and it was successful.

I tried running `mvn spotless:check` and `mvn spotless:apply` and it ran out of memory...
<details><summary>OOM stack</summary>

```
[INFO] --- spotless-maven-plugin:2.20.0:apply (default-cli) @ notion-sdk-jvm-core ---
Nov 14, 2022 10:55:37 AM com.diffplug.spotless.FormatExceptionPolicyLegacy error
SEVERE: Step 'ktfmt' found problem in 'src\main\kotlin\notion\api\v1\model\pages\PagePropertyItem.kt':
Java heap space
java.lang.OutOfMemoryError: Java heap space
        at jdk.internal.jimage.BasicImageReader.getBufferBytes(BasicImageReader.java:339)
        at jdk.internal.jimage.BasicImageReader.getResource(BasicImageReader.java:395)
        at jdk.internal.jimage.ImageReader$SharedImageReader.getResource(ImageReader.java:551)
        at jdk.internal.jimage.ImageReader.getResource(ImageReader.java:109)
        at jdk.internal.jrtfs.SystemImage$1.getResource(SystemImage.java:68)
        at jdk.internal.jrtfs.JrtFileSystem.getFileContent(JrtFileSystem.java:258)
        at jdk.internal.jrtfs.JrtFileSystem.newByteChannel(JrtFileSystem.java:351)
        at jdk.internal.jrtfs.JrtPath.newByteChannel(JrtPath.java:696)
        at jdk.internal.jrtfs.JrtFileSystemProvider.newByteChannel(JrtFileSystemProvider.java:302)
        at java.base/java.nio.file.Files.newByteChannel(Files.java:370)
        at java.base/java.nio.file.Files.newByteChannel(Files.java:421)
        at java.base/java.nio.file.Files.readAllBytes(Files.java:3205)
        at org.jetbrains.kotlin.cli.jvm.modules.CoreJrtVirtualFile.contentsToByteArray(CoreJrtVirtualFile.kt:71)
        at org.jetbrains.kotlin.resolve.jvm.modules.JavaModuleInfo$Companion.read(JavaModuleInfo.kt:61)
        at org.jetbrains.kotlin.cli.jvm.modules.CliJavaModuleFinder.findSystemModule(CliJavaModuleFinder.kt:44)
        at org.jetbrains.kotlin.cli.jvm.modules.CliJavaModuleFinder.access$findSystemModule(CliJavaModuleFinder.kt:25)
        at org.jetbrains.kotlin.cli.jvm.modules.CliJavaModuleFinder$systemModules$1.invoke(CliJavaModuleFinder.kt:37)
        at org.jetbrains.kotlin.cli.jvm.modules.CliJavaModuleFinder$systemModules$1.invoke(CliJavaModuleFinder.kt:37)
        at kotlin.sequences.TransformingSequence$iterator$1.next(Sequences.kt:210)
        at kotlin.sequences.FilteringSequence$iterator$1.calcNext(Sequences.kt:170)
        at kotlin.sequences.FilteringSequence$iterator$1.hasNext(Sequences.kt:194)
        at kotlin.sequences.SequencesKt___SequencesKt.toCollection(_Sequences.kt:786)
        at kotlin.sequences.SequencesKt___SequencesKt.toMutableList(_Sequences.kt:816)
        at kotlin.sequences.SequencesKt___SequencesKt.toList(_Sequences.kt:807)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment.<init>(KotlinCoreEnvironment.kt:244)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment.<init>(KotlinCoreEnvironment.kt)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment$Companion.createForProduction(KotlinCoreEnvironment.kt:425)
        at com.facebook.ktfmt.Parser.parse(Parser.kt:46)
        at com.facebook.ktfmt.FormatterKt.prettyPrint(Formatter.kt:131)
        at com.facebook.ktfmt.FormatterKt.format(Formatter.kt:124)
        at com.facebook.ktfmt.FormatterKt.format(Formatter.kt:105)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
```
</details>

Can you please approve the GitHub Actions CI so it runs `spotless:check`?

---

A few unrelated observations to improve contributor DX:
 * This project has no `mvnw`, which means that the build is not reproducible and it's unclear which version should I use. (e.g. maven 3.1.0 I had didn't work)
 * The build is full of trivially fixable warnings, which means it's really hard to see what's up, are the changes I made actually healthy or not? is not easily answerable. I would worry about this more than spotless.
 * Looks like Maven or spotless needs explicit JVM arguments to set `-Xmx`.
 * I'm on Windows, so that .sh file you linked is not executable, luckily it was a simple `mvn` command.
 * Running `spotless:apply` (for however long it can execute before OOM) rewrites all the line endings on Windows, therefore changes all files.

**Comment by seratch** [comment]
Thanks for taking your time to work on the updates! Also, I appreciate your feedback. As for this PR, you don’t need to use your time further. If there is something to change further, I will fix it after merging this one.

**Comment by seratch** [comment]
I know the code formatter validation fails. If the maven plugin does not work on your machine, I will fix it for you tomorrow

**Comment by TWiStErRob** [comment]
The formatting suggestions of spotless make the code look weird. I'll let you fix it up as you see fit. I really think that this style is error prone and hard to read:
```
        client
            .search(
                query = "Test Database",
                filter = SearchRequest.SearchFilter("database", property = "object"))
            .results
```
vs
```
        client
            .search(
                query = "Test Database",
                filter = SearchRequest.SearchFilter("database", property = "object"),
            )
            .results
```

**Comment by seratch** [comment]
Thanks for your contribution! Your changes have been merged by https://github.com/seratch/notion-sdk-jvm/commit/86e96807d425a3f1ae106267dbdd05f0e8b3a906

**Pull request closed without merging**
