### PR TITLE
Change "Title" property in README to "title"

### PR DESCRIPTION
**Pull request by J-MR-T**
The API seems to be case sensitive with respect to the "title" property and "Title" yields a response code of 400 for me, so I changed it in the README

### CODE REVIEW

**Comment by seratch** [comment]
Perhaps, your test database should have "title" property, not "Title". Can you check that again? 

When I wrote the README, Notion didn't provide database creation API yet. Thus, the code example works only when you have exactly the same name properties in test database. Now that they have an API to create a new database, we can make the code snippet more robust, though.

**Comment by J-MR-T** [comment]
In my test database I did not manually create the title field, it defaulted to "title". But I will run the whole snippet on its own later on and check it again. I'll report back 👍

**Comment by J-MR-T** [comment]
This is the test database I used (I just created it and then the properties, changed nothing else):
image

The example from the README results in this:
```
body    {"object":"error","status":400,"code":"validation_error","message":"Title is not a property that exists."}
Exception in thread "main" notion.api.v1.exception.NotionAPIError: Got an error from Notion (status: 400, code: validation_error, message: Title is not a property that exists.)
```
If I change "Title" to "title" it worrks flawlessly, this is the result:
image

**Comment by seratch** [comment]
@J-MR-T Thanks for sharing this!

My test database has a property named "Title" with Title type. Perhaps, that's why the code example works for me.

**Comment by J-MR-T** [comment]
Ah, okay, can you try changing it to anything else? Because I think "title" implicitly always works, as according to the api docs it is also the id for the name/Title field

**Comment by J-MR-T** [comment]
See here: https://developers.notion.com/reference/database#property-object

**Comment by seratch** [comment]
I see. I just confirmed that "title" also works for me. Let me merge this PR. Thanks!

**Comment by J-MR-T** [comment]
Cool, thank you :D

**Pull request merged**
