### PR TITLE
Deserialize captions on Images and Videos as Rich-Text

### PR DESCRIPTION
**Pull request by looorent**
This PR addresses https://github.com/seratch/notion-sdk-jvm/issues/52

### CODE REVIEW

**Comment by seratch** [comment]
@looorent Can you run the code formatter? `mvn spotless:apply` or `./scripts/format.sh` works for you.

```
Error:  Failed to execute goal com.diffplug.spotless:spotless-maven-plugin:2.20.0:check (default-cli) on project notion-sdk-jvm-core: The following files had format violations:
Error:      src/main/kotlin/notion/api/v1/model/blocks/VideoBlock.kt
Error:          @@ -45,8 +45,8 @@
Error:           ··open·class·Element
Error:           ··@JvmOverloads
Error:           ··constructor(
Error:          -····val·caption:·List<PageProperty.RichText>?·=·null,
Error:          -····val·type:·String?·=·"external",
Error:          -····val·external:·ExternalFileDetails?·=·null,
Error:          +······val·caption:·List<PageProperty.RichText>?·=·null,
Error:          +······val·type:·String?·=·"external",
Error:          +······val·external:·ExternalFileDetails?·=·null,
Error:           ··)
Error:           }
Error:  Run 'mvn spotless:apply' to fix these violations.
Error:  -> [Help 1]
```

**Comment by looorent** [comment]
Sure, it's done.

**Review by seratch — APPROVED** [review]

**Comment by seratch** [comment]
@looorent Thanks for fixing this! Once I've resolved the rest in [this milestone](https://github.com/seratch/notion-sdk-jvm/milestone/15), I will release a new patch version.

**Comment by dmitry-weirdo** [comment]
Is this the same error by me:

```java
body    {"object":"list","results":[{"object":"block","id":"3daf10ea-5b7c-4af9-8d12-544a79931d0e","parent":{"type":"page_id","page_id":"88b6b1a7-a2db-4043-bb0c-5a5d10e8ec14"},"created_time":"2023-01-30T12:54:00.000Z","last_edited_time":"2023-01-30T12:56:00.000Z","created_by":{"object":"user","id":"5e725787-19a8-4728-83a3-ed088839c159"},"last_edited_by":{"object":"user","id":"5e725787-19a8-4728-83a3-ed088839c159"},"has_children":false,"archived":false,"type":"paragraph","paragraph":{"rich_text":[{"type":"text","text":{"content":"UA","link":null},"annotations":{"bold":true,"italic":false,"strikethrough":false,"underline":false,"code":false,"color":"default"},"plain_text":"UA","href":null},{"type":"text","text":{"content":" — ","link":null},"annotations":{"bold":false,"italic":false,"strikethrough":false,"underline":false,"code":false,"color":"default"},"plain_text":" — ","href":null},{"type":"text","text":{"content":"Перші кроки в Німеччині","link":{"url":"/76ab3439eaf448eeb5912c1f2552b743"}},"annotations":{"bold":false,"italic":false,"strikethrough":false,"underline":false,"code":false,"color":"default"},"plain_text":"Перші кроки в Німеччині","href":"/76ab3439eaf448eeb5912c1f2552b743"}],"color":"blue_background"}},{"object":"block","id":"7ec08f9d-ab1f-4ea9-bd69-0e3703cf50e2","parent":{"type":"page_id","page_id":"88b6b1a7-a2db-4043-bb0c-5a5d10e8ec14"},"created_time":"2023-01-30T12:54:00.000Z","last_edited_time":"2023-01-30T12:56:00.000Z","created_by":{"object":"user","id":"5e725787-19a8-4728-83a3-ed088839c159"},"last_edited_by":{"object":"user","id":"5e725787-19a8-4728-83a3-ed088839c159"},"has_children":false,"archived":false,"type":"paragraph","paragraph":{"rich_text":[{"type":"text","text":{"content":"DE ","link":null},"annotations":{"bold":true,"italic":false,"strikethrough":false,"underline":false,"code":false,"color":"default"},"plain_text":"DE ","href":null},{"type":"text","text":{"content":"— ","link":null},"annotations":{"bold":false,"italic":false,"strikethrough":false,"underline":false,"code":false,"color":"default"},"plain_text":"— ","href":null},{"type":"text","text":{"content":"Erste Schritte in Deutschland","link":{"url":"/0a68f323f9e94fe18d93f7854f516a52"}},"annotations":{"bold":true,"italic":false,"strikethrough":false,"underline":false,"code":false,"color":"default"},"plain_text":"Erste Schritte in Deutschland","href":"/0a68f323f9e94fe18d93f7854f516a52"}],"color":"blue_background"}},{"object":"block","id":"ca006708-a88c-470b-8bf1-217c5e5b2199","parent":{"type":"page_id","page_id":"88b6b1a7-a2db-4043-bb0c-5a5d10e8ec14"},"created_time":"2023-01-23T13:49:00.000Z","last_edited_time":"2023-01-23T13:52:00.000Z","created_by":{"object":"user","id":"5e725787-19a8-4728-83a3-ed088839c159"},"last_edited_by":{"object":"user","id":"5e725787-19a8-4728-83a3-ed088839c159"},"has_children":false,"archived":false,"type":"callout","callout":{"rich_text":[{"type":"text","text":{"content":"На канале ","link":null},"annotations":{"bold":false,"italic":false,"strikethrough":false,"underline":false,"code":false,"color":"default"},"plain_text":"На канале ","href":null},{"type":"text","text":{"content":"YouTube.UAhelp","link":{"url":"https://YouTube.com/UAhelp"}},"annotations":{"bold":true,"italic":false,"strikethrough":false,"underline":false,"code":false,"color":"default"},"plain_text":"YouTube.UAhelp","href":"https://YouTube.com/UAhelp"},{"type":"text","text":{"content":" есть ","link":null},"annotations":{"bold":false,"italic":false,"strikethrough":false,"underline":false,"code":false,"color":"default"},"plain_text":" есть ","href":null},{"type":"text","text":{"content":"подборка видео","link":{"url":"https://www.youtube.com/playlist?list=PLdMVuFravFYsqu5MNJhyw-eFAAqyPBhr2"}},"annotations":{"bold":true,"italic":false,"strikethrough":false,"underline":false,"code":false,"color":"default"},"plain_text":"подборка видео","href":"https://www.youtube.com/playlist?list=PLdMVuFravFYsqu5MNJhyw-eFAAqyPBhr2"},{"type":"text","text":{"content":" по этой теме.","link":null},"annotations":{"bold":false,"italic":false,"strikethrough":false,"underline":false,"code":false,"color":"default"},"plain_text":" по этой теме.","href":null}],"icon":{"type":"emoji","emoji":"📺"},"color":"yellow_background"}},{"object":"block","id":"d2c6782b-ca3c-4930-b41f-88b4ecdafc5a","parent":{"type":"page_id","page_id":"88b6b1a7-a2db-4043-bb0c-5a5d10e8ec14"},"created_time":"2023-01-30T12:47:00.000Z","last_edited_time":"2023-05-22T17:19:00.000Z","created_by":{"object":"user","id":"5e725787-19a8-4728-83a3-ed088839c159"},"last_edited_by":{"object":"user","id":"c86ae61a-bc93-42ff-97a8-badf2d511fe6"},"has_children":false,"archived":false,"type":"paragraph","paragraph":{"rich_text":[{"type":"text","text":{"content":"Дата последнего обновления: 22.05.2023","link":null},"annotations":{"bold":false,"italic":true,"strikethrough":false,"underline":false,"code":false,"color":"default"},"plain_text":"Дата последнего обновления: 22.05.2023","href":null}],"color":"default"}},{"object":"block","id":"4d427f7f-c125-4eac-bcfc-b6528aa93f81","parent":{"type":"page_id","page_id":"88b6b1a7-a2db-4043-bb0c-5a5d10e8ec14"},"created_time":"2023-05-22T16:51:00.000Z","last_edited_time":"2023-05-22T16:52:00.000Z","created_by":{"object":"user","id":"c86ae61a-bc93-42ff-97a8-badf2d511fe6"},"last_edited_by":{"object":"user","id":"c86ae61a-bc93-42ff-97a8-badf2d511fe6"},"has_children":false,"archived":false,"type":"heading_1","heading_1":{"rich_text":[{"type":"text","text":{"content":"Вы приехали в Германию, с чего начать? ","link":null},"annotations":{"bold":false,"italic":false,"strikethrough":false,"underline":false,"code":false,"color":"default"},"plain_text":"Вы приехали в Германию, с чего начать? ","href":null}],"is_toggleable":false,"color":"default"}},{"object":"block","id":"4bd74947-2b55-4f5b-beb5-8b2b2ad5f3ca","parent":{"type":"page_id","page_id":"88b6b1a7-a2db-4043-bb0c-5a5d10e8ec14"},"created_time":"2023-05-22T16:52:00.000Z","last_edited_time":"2023-05-22T17:36:00.000Z","created_by":{"object":"user","id":"c86ae61a-bc93-42ff-97a8-badf2d511fe6"},"last_edited_by":{"object":"user","id":"c86ae61a-bc93-42ff-97a8-badf2d511fe6"},"has_children":true,"archived":false,"type":"bulleted_list_item","bulleted_list_item":{"rich_text":[{"type":"text","text":{"content":"Порядок действий","link":null},"annotations":{"bold":true,"italic":false,"strikethrough":false,"underline":false,"code":false,"color":"default"},"plain_text":"Порядок действий","href":null},{"type":"text","text":{"content":" на примере крупных городов:","link":null},"annotations":{"bold":false,"italic":false,"strikethrough":false,"underline":false,"code":false,"color":"default"},"plain_text":" на примере крупных городов:","href":null}],"color":"default"}},{"object":"block","id":"3d28972b-1ceb-4c1b-bdff-cebd12025abf","parent":{"type":"page_id","page_id":"88b6b1a7-a2db-4043-bb0c-5a5d10e8ec14"},"created_time":"2023-05-22T17:35:00.000Z","last_edited_time":"2023-05-22T17:36:00.000Z","created_by":{"object":"user","id":"c86ae61a-bc93-42ff-97a8-badf2d511fe6"},"last_edited_by":{"object":"user","id":"c86ae61a-bc93-42ff-97a8-badf2d511fe6"},"has_children":true,"archived":false,"type":"bulleted_list_item","bulleted_list_item":{"rich_text":[{"type":"text","text":{"content":"Вот еще примеры хорошо структурированных и понятных описаний порядка действий","link":null},"annotations":{"bold":false,"italic":false,"strikethrough":false,"underline":false,"code":false,"color":"default"},"plain_text":"Вот еще примеры хорошо структурированных и понятных описаний порядка действий","href":null}],"color":"default"}},{"object":"block","id":"83f44375-d1a8-4beb-b491-86b168ecf9e9","parent":{"type":"page_id","page_id":"88b6b1a7-a2db-4043-bb0c-5a5d10e8ec14"},"created_time":"2023-05-22T16:51:00.000Z","last_edited_time":"2023-05-22T17:36:00.000Z","created_by":{"object":"user","id":"c86ae61a-bc93-42ff-97a8-badf2d511fe6"},"last_edited_by":{"object":"user","id":"c86ae61a-bc93-42ff-97a8-badf2d511fe6"},"has_children":false,"archived":false,"type":"bulleted_list_item","bulleted_list_item":{"rich_text":[{"type":"text","text":{"content":"Что вас ждет после приезда","link":null},"annotations":{"bold":true,"italic":false,"strikethrough":false,"underline":false,"code":false,"color":"default"},"plain_text":"Что вас ждет после приезда","href":null},{"type":"text","text":{"content":" — ","link":null},"annotations":{"bold":false,"italic":false,"strikethrough":false,"underline":false,"code":false,"color":"default"},"plain_text":" — ","href":null},{"type":"text","text":{"content":"https://uahelp.wiki/stuttgart/expect","link":{"url":"https://uahelp.wiki/stuttgart/expect"}},"annotations":{"bold":false,"italic":false,"strikethrough":false,"underline":false,"code":false,"color":"default"},"plain_text":"https://uahelp.wiki/stuttgart/expect","href":"https://uahelp.wiki/stuttgart/expect"},{"type":"text","text":{"content":" ","link":null},"annotations":{"bold":false,"italic":false,"strikethrough":false,"underline":false,"code":false,"color":"default"},"plain_text":" ","href":null}],"color":"default"}},{"object":"block","id":"17e9073e-25fb-4d3e-80b0-8f4e7f529cb1","parent":{"type":"page_id","page_id":"88b6b1a7-a2db-4043-bb0c-5a5d10e8ec14"},"created_time":"2023-01-30T07:37:00.000Z","last_edited_time":"2023-05-22T16:55:00.000Z","created_by":{"object":"user","id":"5e725787-19a8-4728-83a3-ed088839c159"},"last_edited_by":{"object":"user","id":"c86ae61a-bc93-42ff-97a8-badf2d511fe6"},"has_children":false,"archived":false,"type":"heading_1","heading_1":{"rich_text":[{"type":"text","text":{"content":"См. также","link":null},"annotations":{"bold":false,"italic":false,"strikethrough":false,"underline":false,"code":false,"color":"default"},"plain_text":"См. также","href":null}],"is_toggleable":false,"color":"default"}},{"object":"block","id":"a4d8bcf6-e854-4c4b-b133-32bcf04c171a","parent":{"type":"page_id","page_id":"88b6b1a7-a2db-4043-bb0c-5a5d10e8ec14"},"created_time":"2023-01-30T07:36:00.000Z","last_edited_time":"2023-01-30T07:36:00.000Z","created_by":{"object":"user","id":"5e725787-19a8-4728-83a3-ed088839c159"},"last_edited_by":{"object":"user","id":"5e725787-19a8-4728-83a3-ed088839c159"},"has_children":false,"archived":false,"type":"link_to_page","link_to_page":{"type":"page_id","page_id":"4123242e-daca-4d4e-af94-fe4955c06132"}},{"object":"block","id":"2fedcf75-2c83-4abf-b8b9-6c16ae7c0b08","parent":{"type":"page_id","page_id":"88b6b1a7-a2db-4043-bb0c-5a5d10e8ec14"},"created_time":"2023-01-30T07:39:00.000Z","last_edited_time":"2023-05-22T16:56:00.000Z","created_by":{"object":"user","id":"5e725787-19a8-4728-83a3-ed088839c159"},"last_edited_by":{"object":"user","id":"c86ae61a-bc93-42ff-97a8-badf2d511fe6"},"has_children":false,"archived":false,"type":"link_to_page","link_to_page":{"type":"page_id","page_id":"49df17a4-32e7-4a84-8436-373a9f293ffa"}},{"object":"block","id":"241db186-5465-418c-92ee-03804abb8468","parent":{"type":"page_id","page_id":"88b6b1a7-a2db-4043-bb0c-5a5d10e8ec14"},"created_time":"2023-01-30T07:51:00.000Z","last_edited_time":"2023-05-22T16:54:00.000Z","created_by":{"object":"user","id":"5e725787-19a8-4728-83a3-ed088839c159"},"last_edited_by":{"object":"user","id":"c86ae61a-bc93-42ff-97a8-badf2d511fe6"},"has_children":true,"archived":false,"type":"child_page","child_page":{"title":"Различия между статусом беженца и временной защитой по п.24 в Германии"}},{"object":"block","id":"2ef95621-fc6e-47f6-8d42-ddeb9bf6fa7b","parent":{"type":"page_id","page_id":"88b6b1a7-a2db-4043-bb0c-5a5d10e8ec14"},"created_time":"2023-05-22T16:58:00.000Z","last_edited_time":"2023-05-22T17:00:00.000Z","created_by":{"object":"user","id":"c86ae61a-bc93-42ff-97a8-badf2d511fe6"},"last_edited_by":{"object":"user","id":"c86ae61a-bc93-42ff-97a8-badf2d511fe6"},"has_children":true,"archived":false,"type":"child_page","child_page":{"title":"Официальные ссылки"}},{"object":"block","id":"a855a0a1-7bcc-4401-9c7b-fdc29a7f5279","parent":{"type":"page_id","page_id":"88b6b1a7-a2db-4043-bb0c-5a5d10e8ec14"},"created_time":"2022-05-29T12:29:00.000Z","last_edited_time":"2023-05-22T16:57:00.000Z","created_by":{"object":"user","id":"7525ec4c-c663-46b1-8460-edd4b4b8a85d"},"last_edited_by":{"object":"user","id":"c86ae61a-bc93-42ff-97a8-badf2d511fe6"},"has_children":false,"archived":false,"type":"paragraph","paragraph":{"rich_text":[{"type":"mention","mention":{"type":"page","page":{"id":"cc5847d2-198a-4d46-8078-5d63ab86012c"}},"annotations":{"bold":false,"italic":false,"strikethrough":false,"underline":false,"code":false,"color":"default"},"plain_text":"Словарик для выживания в 🇩🇪 Германии","href":"https://www.notion.so/cc5847d2198a4d4680785d63ab86012c"},{"type":"text","text":{"content":" ","link":null},"annotations":{"bold":false,"italic":false,"strikethrough":false,"underline":false,"code":false,"color":"default"},"plain_text":" ","href":null}],"color":"default"}},{"object":"block","id":"73bc14b1-7fd9-49a9-916f-0a859b71a184","parent":{"type":"page_id","page_id":"88b6b1a7-a2db-4043-bb0c-5a5d10e8ec14"},"created_time":"2022-05-20T18:08:00.000Z","last_edited_time":"2023-05-22T16:56:00.000Z","created_by":{"object":"user","id":"7525ec4c-c663-46b1-8460-edd4b4b8a85d"},"last_edited_by":{"object":"user","id":"c86ae61a-bc93-42ff-97a8-badf2d511fe6"},"has_children":false,"archived":false,"type":"paragraph","paragraph":{"rich_text":[{"type":"mention","mention":{"type":"page","page":{"id":"90a7eef5-d805-4bbc-ae99-f232e5526fa5"}},"annotations":{"bold":false,"italic":false,"strikethrough":false,"underline":false,"code":false,"color":"default"},"plain_text":"Untitled","href":"https://www.notion.so/90a7eef5d8054bbcae99f232e5526fa5"},{"type":"text","text":{"content":" ","link":null},"annotations":{"bold":false,"italic":false,"strikethrough":false,"underline":false,"code":false,"color":"default"},"plain_text":" ","href":null}],"color":"default"}},{"object":"block","id":"54f40d3c-10eb-4cee-8485-cd2fb604b04c","parent":{"type":"page_id","page_id":"88b6b1a7-a2db-4043-bb0c-5a5d10e8ec14"},"created_time":"2023-01-30T07:37:00.000Z","last_edited_time":"2023-05-22T17:00:00.000Z","created_by":{"object":"user","id":"5e725787-19a8-4728-83a3-ed088839c159"},"last_edited_by":{"object":"user","id":"c86ae61a-bc93-42ff-97a8-badf2d511fe6"},"has_children":false,"archived":false,"type":"link_to_page","link_to_page":{"type":"page_id","page_id":"bd9ef9a8-0472-4362-a97f-a23ece97f3d1"}},{"object":"block","id":"344a1f1a-3582-462c-a782-53880c1cbb1e","parent":{"type":"page_id","page_id":"88b6b1a7-a2db-4043-bb0c-5a5d10e8ec14"},"created_time":"2023-01-30T13:34:00.000Z","last_edited_time":"2023-01-30T13:34:00.000Z","created_by":{"object":"user","id":"5e725787-19a8-4728-83a3-ed088839c159"},"last_edited_by":{"object":"user","id":"5e725787-19a8-4728-83a3-ed088839c159"},"has_children":false,"archived":false,"type":"heading_1","heading_1":{"rich_text":[{"type":"text","text":{"content":"Видео","link":null},"annotations":{"bold":false,"italic":false,"strikethrough":false,"underline":false,"code":false,"color":"default"},"plain_text":"Видео","href":null}],"is_toggleable":false,"color":"default"}},{"object":"block","id":"32371297-07a3-4e6e-96d4-0dfa37870a83","parent":{"type":"page_id","page_id":"88b6b1a7-a2db-4043-bb0c-5a5d10e8ec14"},"created_time":"2023-01-23T14:01:00.000Z","last_edited_time":"2023-01-30T07:38:00.000Z","created_by":{"object":"user","id":"5e725787-19a8-4728-83a3-ed088839c159"},"last_edited_by":{"object":"user","id":"5e725787-19a8-4728-83a3-ed088839c159"},"has_children":false,"archived":false,"type":"video","video":{"caption":[{"type":"text","text":{"content":"Первые шаги в Германии - пошаговая инструкция, 02.11.2022","link":null},"annotations":{"bold":false,"italic":false,"strikethrough":false,"underline":false,"code":false,"color":"default"},"plain_text":"Первые шаги в Германии - пошаговая инструкция, 02.11.2022","href":null}],"type":"external","external":{"url":"https://www.youtube.com/watch?v=Y8UhqgO7KUA"}}},{"object":"block","id":"82196622-fc9a-4eec-9a14-792f40d2ad89","parent":{"type":"page_id","page_id":"88b6b1a7-a2db-4043-bb0c-5a5d10e8ec14"},"created_time":"2023-01-30T07:53:00.000Z","last_edited_time":"2023-01-30T07:56:00.000Z","created_by":{"object":"user","id":"5e725787-19a8-4728-83a3-ed088839c159"},"last_edited_by":{"object":"user","id":"5e725787-19a8-4728-83a3-ed088839c159"},"has_children":false,"archived":false,"type":"callout","callout":{"rich_text":[{"type":"text","text":{"content":"На выходных государственные ведомства закрыты (в том числе ведомства по миграции). Если вы не знаете, куда идти, помощь с направлением в ближайший лагерь для беженцев может оказать федеральная полиция (Bundespolizei). Ее представители есть на границах, вокзалах, в аэропортах и доступны 24 часа в сутки.","link":null},"annotations":{"bold":false,"italic":false,"strikethrough":false,"underline":false,"code":false,"color":"default"},"plain_text":"На выходных государственные ведомства закрыты (в том числе ведомства по миграции). Если вы не знаете, куда идти, помощь с направлением в ближайший лагерь для беженцев может оказать федеральная полиция (Bundespolizei). Ее представители есть на границах, вокзалах, в аэропортах и доступны 24 часа в сутки.","href":null}],"icon":{"type":"emoji","emoji":"👮🏻"},"color":"gray_background"}},{"object":"block","id":"8a7667fa-062d-4e1c-9256-81f57cd8b9b0","parent":{"type":"page_id","page_id":"88b6b1a7-a2db-4043-bb0c-5a5d10e8ec14"},"created_time":"2023-01-30T07:42:00.000Z","last_edited_time":"2023-05-22T17:00:00.000Z","created_by":{"object":"user","id":"5e725787-19a8-4728-83a3-ed088839c159"},"last_edited_by":{"object":"user","id":"c86ae61a-bc93-42ff-97a8-badf2d511fe6"},"has_children":false,"archived":false,"type":"heading_1","heading_1":{"rich_text":[{"type":"text","text":{"content":"Прочие ссылки","link":null},"annotations":{"bold":false,"italic":false,"strikethrough":false,"underline":false,"code":false,"color":"default"},"plain_text":"Прочие ссылки","href":null}],"is_toggleable":false,"color":"default"}},{"object":"block","id":"b82114c7-88da-46e7-a304-4fdfdab14a68","parent":{"type":"page_id","page_id":"88b6b1a7-a2db-4043-bb0c-5a5d10e8ec14"},"created_time":"2022-05-20T18:03:00.000Z","last_edited_time":"2023-01-30T12:42:00.000Z","created_by":{"object":"user","id":"7525ec4c-c663-46b1-8460-edd4b4b8a85d"},"last_edited_by":{"object":"user","id":"5e725787-19a8-4728-83a3-ed088839c159"},"has_children":false,"archived":false,"type":"paragraph","paragraph":{"rich_text":[{"type":"mention","mention":{"type":"page","page":{"id":"7e574da9-690b-4ad3-bb0f-cb6252ccab22"}},"annotations":{"bold":false,"italic":false,"strikethrough":false,"underline":false,"code":false,"color":"default"},"plain_text":"Сим-карты | SIM cards","href":"https://www.notion.so/7e574da9690b4ad3bb0fcb6252ccab22"},{"type":"text","text":{"content":" ","link":null},"annotations":{"bold":false,"italic":false,"strikethrough":false,"underline":false,"code":false,"color":"default"},"plain_text":" ","href":null}],"color":"default"}},{"object":"block","id":"cbb94a7e-8bdb-4437-a898-809aa44531d2","parent":{"type":"page_id","page_id":"88b6b1a7-a2db-4043-bb0c-5a5d10e8ec14"},"created_time":"2023-01-30T12:48:00.000Z","last_edited_time":"2023-05-22T16:57:00.000Z","created_by":{"object":"user","id":"5e725787-19a8-4728-83a3-ed088839c159"},"last_edited_by":{"object":"user","id":"c86ae61a-bc93-42ff-97a8-badf2d511fe6"},"has_children":false,"archived":false,"type":"paragraph","paragraph":{"rich_text":[],"color":"default"}},{"object":"block","id":"53150c92-7f86-4fd5-acf0-0fc0ee106beb","parent":{"type":"page_id","page_id":"88b6b1a7-a2db-4043-bb0c-5a5d10e8ec14"},"created_time":"2022-05-30T18:49:00.000Z","last_edited_time":"2022-05-30T18:49:00.000Z","created_by":{"object":"user","id":"7525ec4c-c663-46b1-8460-edd4b4b8a85d"},"last_edited_by":{"object":"user","id":"7525ec4c-c663-46b1-8460-edd4b4b8a85d"},"has_children":false,"archived":false,"type":"divider","divider":{}},{"object":"block","id":"e5d4d0cd-781d-4d25-a729-66db999694fc","parent":{"type":"page_id","page_id":"88b6b1a7-a2db-4043-bb0c-5a5d10e8ec14"},"created_time":"2022-05-30T18:49:00.000Z","last_edited_time":"2023-01-30T14:44:00.000Z","created_by":{"object":"user","id":"7525ec4c-c663-46b1-8460-edd4b4b8a85d"},"last_edited_by":{"object":"user","id":"5e725787-19a8-4728-83a3-ed088839c159"},"has_children":true,"archived":false,"type":"toggle","toggle":{"rich_text":[{"type":"text","text":{"content":"Страницы в этом разделе","link":null},"annotations":{"bold":false,"italic":false,"strikethrough":false,"underline":false,"code":false,"color":"default"},"plain_text":"Страницы в этом разделе","href":null}],"color":"default"}},{"object":"block","id":"2bc0aa41-1883-4a86-a1b4-4ea077114c6f","parent":{"type":"page_id","page_id":"88b6b1a7-a2db-4043-bb0c-5a5d10e8ec14"},"created_time":"2022-05-30T18:54:00.000Z","last_edited_time":"2023-01-23T14:00:00.000Z","created_by":{"object":"user","id":"7525ec4c-c663-46b1-8460-edd4b4b8a85d"},"last_edited_by":{"object":"user","id":"5e725787-19a8-4728-83a3-ed088839c159"},"has_children":false,"archived":false,"type":"paragraph","paragraph":{"rich_text":[],"color":"default"}},{"object":"block","id":"3b21cae2-16d7-49b9-8714-fcccbb403098","parent":{"type":"page_id","page_id":"88b6b1a7-a2db-4043-bb0c-5a5d10e8ec14"},"created_time":"2022-05-30T18:54:00.000Z","last_edited_time":"2023-01-23T14:00:00.000Z","created_by":{"object":"user","id":"7525ec4c-c663-46b1-8460-edd4b4b8a85d"},"last_edited_by":{"object":"user","id":"5e725787-19a8-4728-83a3-ed088839c159"},"has_children":false,"archived":false,"type":"paragraph","paragraph":{"rich_text":[{"type":"text","text":{"content":"Обратно на главную страницу ","link":null},"annotations":{"bold":false,"italic":false,"strikethrough":false,"underline":false,"code":false,"color":"default"},"plain_text":"Обратно на главную страницу ","href":null},{"type":"mention","mention":{"type":"page","page":{"id":"2b4f00e8-0cb9-4440-af00-e8d83b758f27"}},"annotations":{"bold":false,"italic":false,"strikethrough":false,"underline":false,"code":false,"color":"default"},"plain_text":"Помощь украинцам в Германии","href":"https://www.notion.so/2b4f00e80cb94440af00e8d83b758f27"},{"type":"text","text":{"content":"  ","link":null},"annotations":{"bold":false,"italic":false,"strikethrough":false,"underline":false,"code":false,"color":"default"},"plain_text":"  ","href":null}],"color":"default"}},{"object":"block","id":"9bd25eef-12b5-4a27-8a64-f6530dd57f9d","parent":{"type":"page_id","page_id":"88b6b1a7-a2db-4043-bb0c-5a5d10e8ec14"},"created_time":"2022-09-19T17:35:00.000Z","last_edited_time":"2022-12-04T19:13:00.000Z","created_by":{"object":"user","id":"f390f401-5ef8-4e5a-94c5-2efa5bf4b350"},"last_edited_by":{"object":"user","id":"c86ae61a-bc93-42ff-97a8-badf2d511fe6"},"has_children":true,"archived":false,"type":"heading_1","heading_1":{"rich_text":[{"type":"text","text":{"content":"**  Неразобранное","link":null},"annotations":{"bold":false,"italic":false,"strikethrough":false,"underline":false,"code":false,"color":"default"},"plain_text":"**  Неразобранное","href":null}],"is_toggleable":true,"color":"default"}}],"next_cursor":null,"has_more":false,"type":"block","block":{}}
[ERROR] 2023-06-18 11:15:36.934 [main] NotionPageTree - Error when getting children for block 88b6b1a7a2db4043bb0c5a5d10e8ec14
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected STRING but was BEGIN_OBJECT at path $.video.caption[0]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:226) ~[gson-2.8.7.jar:?]
```

The video json returned looks like this:
```json
      "video": {
        "caption": [
          {
            "type": "text",
            "text": {
              "content": "Первые шаги в Германии - пошаговая инструкция, 02.11.2022",
              "link": null
            },
            "annotations": {
              "bold": false,
              "italic": false,
              "strikethrough": false,
              "underline": false,
              "code": false,
              "color": "default"
            },
            "plain_text": "Первые шаги в Германии - пошаговая инструкция, 02.11.2022",
            "href": null
          }
        ],
        "type": "external",
        "external": {
          "url": "https://www.youtube.com/watch?v=Y8UhqgO7KUA"
        }
      }
```

**Pull request merged**
